### ISSUE TITLE
i approve

### ISSUE THREAD

**Issue by jwklong** [Alpha-404/Roblox-Scripts#1]
i approve this script as good because i am the creator of std+

also there's a bug where i actually removed the script

**Comment by jwklong** [comment]
may or may not add it back

**Comment by jwklong** [comment]
also when you say copied a bunch of my code you mean 1 gui and 1 script

**Comment by jwklong** [comment]
also if u want another video about it sure, 7:00 gmt

**Comment by Alpha-404** [comment]
the script works fine also why did you fork it?

**Comment by jwklong** [comment]
> @Alpha-404  the script works fine also why did you fork it?

forked it to make a pull request about deleting the file

**Comment by Alpha-404** [comment]
I will leave it as part of the history of my scripts

**Comment by jwklong** [comment]
> @Alpha-404  I will leave it as part of the history of my scripts
at least mark it as something like (NO LONGER WORKS)

**Comment by Alpha-404** [comment]
Alr ig

**Comment by jwklong** [comment]
ok im done with this
